"""add_vote_deadline

Revision ID: 543574e1221e
Revises: d48c19a52460
Create Date: 2026-02-20 19:23:33.497740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543574e1221e'
down_revision: Union[str, None] = 'd48c19a52460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('vote_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'vote_deadline')
    # ### end Alembic commands ###
