"""add_reminders_and_user_settings

Revision ID: c5340e7bc402
Revises: 543574e1221e
Create Date: 2026-02-20 21:58:47.491614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5340e7bc402'
down_revision: Union[str, None] = '543574e1221e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('reminder_minutes', sa.SmallInteger(), nullable=True))
    op.add_column('meetings', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('meetings', sa.Column('deadline_reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('schedule_remind', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('schedule_remind_day', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('schedule_remind_hour', sa.SmallInteger(), server_default='12', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'schedule_remind_hour')
    op.drop_column('users', 'schedule_remind_day')
    op.drop_column('users', 'schedule_remind')
    op.drop_column('meetings', 'deadline_reminder_sent')
    op.drop_column('meetings', 'reminder_sent')
    op.drop_column('meetings', 'reminder_minutes')
    # ### end Alembic commands ###
