"""add_recurrence_to_meetings

Revision ID: fb029e259715
Revises: c5340e7bc402
Create Date: 2026-02-21 02:31:43.496077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb029e259715'
down_revision: Union[str, None] = 'c5340e7bc402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('recurrence', sa.String(length=20), server_default='none', nullable=False))
    op.add_column('meetings', sa.Column('parent_meeting_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meetings', 'meetings', ['parent_meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'parent_meeting_id')
    op.drop_column('meetings', 'recurrence')
    # ### end Alembic commands ###
